#server:
#  port: 8090
#spring:
#  mvc:
#    favicon:
#      enabled: false
#  datasource:
#    username: root
#    password:
#    url: jdbc:mysql://awspj.c4u5s4ejhnwe.us-east-1.rds.amazonaws.com:3306/
#  jpa:
#    hibernate:
#      ddl-auto:  update
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss

cloud:
  aws:
    credentials:
      access-key:
      secret-key:
      session-token:
    region:
      static:
    end-point:
      url:
    stack:
      auto:

application:
  bucket:
    name:
