server:
  port: 8090
spring:
  mvc:
    favicon:
      enabled: false
  datasource:
    username: root
    password: 23d78yyf
    url: jdbc:mysql://127.0.0.1:3306/photoshop?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto:  update
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


cloud:
  aws:
    credentials:
      access-key: ASIA4N4NQHJOQS4WJF7Y
      secret-key: 04SxM2+VwctWFiHPpRPwZWH9MvvNz8lwRNmOrzGx
      session-token: FwoGZXIvYXdzEOz//////////wEaDFFtFlz5MzZfXA2riCLDAflRwjsNEYc4svnS4HjOeHiDhWnSUQIaw0utOLrAP0LI4z8idKNuwNnxaKMvCH8hNwz0cbi+Uh/4sGhmDiY+e9GzBlh3IJcNMYLlZByFPaz/ytD6MEkLrqFHu+Pb7FNIsy9enhPrd8HlhdkaNlejwZwCa+kh8v24WjQOFfB4yPAlkSlcySuXhxe6LoSL9y0DXhY9WirFFafGvso7uMUb2v2ZJuqYLpIaALGR2mH8cGM3axilGIIW3DI0V7Mf5VTvvU7xkCjNjuWHBjItSAi7wzIN6suN7li+BtYlVeMffSMYCzniJi8k6uBNQrEnM7Cava0hWChipFws
    region:
      static: us-east-1
    end-point:
      url: dynamodb.us-east-1.amazonaws.com
    stack:
      auto: false

application:
  bucket:
    name: addphoto
