#server:
#  port: 8090
#spring:
#  mvc:
#    favicon:
#      enabled: false
#  datasource:
#    username: root
#    password: 23d78yyf
#    url: jdbc:mysql://awspj.c4u5s4ejhnwe.us-east-1.rds.amazonaws.com:3306/
#  jpa:
#    hibernate:
#      ddl-auto:  update
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss

cloud:
  aws:
    credentials:
      access-key: ASIA4N4NQHJOQAJHHM5U
      secret-key: KfxNtZRdkxk4G/zpxLFgzmb7cOE4dFE5ey2nt9O0
      session-token: FwoGZXIvYXdzEAMaDDdvOP0bWN31XK3SCiLDAWiG4d5l7XclE+QRlk4NzYgomGJ9TsPvW33fu9bHkqVA1D5oQRElvIYMYKV6yZKAKSFyOqkxFyDbDN+6P1IZm7Whpmp2gz+hREH+5afIcYZPQg+s/FB+9Yr1/8CDISL/NGsIMwvreaJuaF+78IDQovha5jGm0nNofa5d8lzK1rSivWQQ6QDnGoHdjFTQeuLDpD4wvKsX/1czp59I5W0Z6AxCQZGNw4jl9v9ecOE/wRz9gMQvgM/cYN7LCHVuKb41PqnTJCjcn+qHBjIt3zLPk3a080g7alUXrc7YTl8vpwl25sC1EOPgql857OqHhfXgdoFPqYPD0/ZB
    region:
      static: us-east-1
    end-point:
      url: dynamodb.us-east-1.amazonaws.com
    stack:
      auto: false

application:
  bucket:
    name: addphoto
