server:
  port: 8090
spring:
  mvc:
    favicon:
      enabled: false
  datasource:
    username: root
    password: 23d78yyf
    url: jdbc:mysql://127.0.0.1:3306/photoshop?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto:  update
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


cloud:
  aws:
    credentials:
      access-key: ASIA4N4NQHJOTCLYXMHC
      secret-key: 9lDx/PK9YHgs1mWeMr51BxlWCNd+sausFcaiWq50
      session-token: FwoGZXIvYXdzEMv//////////wEaDET3JLIQq0xrxRYpYiLDAVwzLKfUnNH721lqTPqWCXLBVymj56F7N9xJtnqluIj+m24aywwGxreIRFRp5RcbrElXA91RphMmrmX0jqFvNFFcrR3fCoxmlIYYzBYHsdPfbLfJw0FILMikfun7WuaVHIW5PiQrzTXt2v9gg8J7oJYYJk59j/cq15+MgJlSDYMlKgZl0TXkFQ8rQ5XQeVIynxgH3V+TON4q9/hCd+IBNEJZIn/WyF2p7HxcpwRJJKkYaDHY+dBNEmasjjgdciAGj6qknyjKgN6HBjItKlasZYbdOSpuLui0WErHUoLPOzQv/DoqylLETneY2kH2PtoPaPH3GB6A9Iw3
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: addphoto