server:
  port: 8090
spring:
  mvc:
    favicon:
      enabled: false
  datasource:
    username: root
    password: 23d78yyf
    url: jdbc:mysql://127.0.0.1:3306/photoshop?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto:  update
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


cloud:
  aws:
    credentials:
      access-key: ASIA4N4NQHJO2MBJDTYI
      secret-key: TlqCLlEWK7bdPdaUW0+pxgrLXiZFBpVcSa664LaB
      session-token: FwoGZXIvYXdzEM7//////////wEaDKR7rGwlHixfpCWlgSLDASysdUIIyVhz52I/w/bhJ/67tWeR0eFj/XWhkNqr/+JIRcHUJOcM+ntzD4alrVXILznarWjIraIfBpCwmRaUBcobo6icWMTyovadR82LlTNWt3HEOU5S6UDS4ONPXZ6T6Uc6wVg6YpVVNz8wSDQl0lcbv3WTIqc/1DrBIOR+4ukjPfkDR+S/zZBvqBldiNE7iqWNHXWUCeNzRYsChoiHqUXaLurKAYOOxdsEIPCRU4mzvcfFxdYbctgKgctJ8oQ8CLGKBSip0t6HBjItqVEbEqcFeWv+cROy4k9mB2EeEZfNUVR9ZuRD4rc4odhET15S+hlwsh4gkpCM
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: addphoto